/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

// IDC_STATICはそのまま使用してはいけない（IDC_STATIC = -1、-1は特別？？）
BEGIN_WINDOW_MAP(DEFAULT)
	// 行グループの開始 OK/CANCELボタン行・それ以外の行
	// 全てのコントロールはダイアログエッジから4ピクセルずつ離す
	BEGINROWS(WRCT_REST, 0, RCMARGINS(4,4))
		// 列グループの開始（ツリービューとそれ以外）
		BEGINCOLS(WRCT_REST, 0, RCMARGINS(0,0))
			RCTOFIT(IDC_TREE1)
			RCFIXED(IDC_SIZERBAR, 4)
			BEGINROWS(WRCT_REST, 0, RCMARGINS(0,0)) // 行グループの開始（コンボボックスとグループボックス）
				RCTOFIT(IDC_COMBO1)
				RCSPACE(4) // コンボボックスをグループボックスの間は4ピクセル離す
				BEGINROWS(WRCT_REST, IDC_STATIC2, RCMARGINS(0,0)) // グループボックス
					RCSPACE(12) // グループボックスのラベルを考慮してちょっと離す
					// そのままだとグループボックスのエッジに張り付いてしまうので、
					// グループボックス内のコントロールは全て8ピクセルずつエッジから離す
					BEGINROWS(WRCT_REST, 0, RCMARGINS(8,8))
						BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(0,0))
							RCTOFIT(IDC_STATIC3)
							RCSPACE(4)
							RCREST(IDC_EDIT1)
						ENDGROUP()
						BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(0,4))
							RCREST(IDC_COMBO2)
							RCSPACE(4)
							RCTOFIT(IDC_BUTTON1)
						ENDGROUP()
						RCREST(IDC_LIST2)
					ENDGROUP()
				ENDGROUP()
			ENDGROUP()
		ENDGROUP()
		RCSPACE(4)
		BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(0,0)) // 列グループの開始（OKとCACEL）
			RCREST(-1) // 左側を空ける
			RCTOFIT(IDOK)
			RCSPACE(4) // 4ピクセル分あける
			RCTOFIT(IDCANCEL)
		ENDGROUP()
	ENDGROUP()
END_WINDOW_MAP()
