/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

#pragma once

/// 仕向け先を表す列挙形の定義
enum Customer
{
	PEC,					// パイオニア（ホンダ(TR)と共通）
	PEC_NO_SPECIFIC_TOLL,	// パイオニア（ETC距離別料金非対応）
	TF,						// 三菱電機
	BT_KIWIC,				// クラリオン(KIWI-C)
	BE,						// XANAVI
	MF,						// MF月度
	SHP05,					// 05Shape
	OTHERS,					// その他
};

