/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

#pragma once

namespace hwy_convert_lib
{
	typedef std::shared_ptr< SINDY2INHWYINFO >		SPSINDY2INHWYINFO;
	typedef std::shared_ptr< SindyDBConnection >	SPSindyDBConnection;

	typedef std::shared_ptr< SINDY2HIGHWAY >		SPSINDY2HIGHWAY;
	typedef std::shared_ptr< SINDY2GS >				SPSINDY2GS;
	typedef std::shared_ptr< SINDY2ROADCODE >		SPSINDY2ROADCODE;
	typedef std::shared_ptr< SINDY2ROADPOINT >		SPSINDY2ROADPOINT;
	typedef std::shared_ptr< SINDY2HWYNODE >		SPSINDY2HWYNODE;
	typedef std::shared_ptr< SINDY2HWYSAME >		SPSINDY2HWYSAME;
	typedef std::shared_ptr< SINDY2TOLLGATELANE >	SPSINDY2TOLLGATELANE;

} // namespace hwy_convert_lib
