/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

// SindyBaseMesh.h: SindyBaseMesh クラスのインターフェイス
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_SINDYBASEMESH_H__DCE4F6D4_007B_4761_A185_F03D0CAF8B1B__INCLUDED_)
#define AFX_SINDYBASEMESH_H__DCE4F6D4_007B_4761_A185_F03D0CAF8B1B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "SindyMeshFeature.h"

class SindyBaseMesh : public SindyMeshFeature  
{
public:
	SindyBaseMesh(SindyDBConnection *cDBConnection);
	virtual ~SindyBaseMesh();

};

#endif // !defined(AFX_SINDYBASEMESH_H__DCE4F6D4_007B_4761_A185_F03D0CAF8B1B__INCLUDED_)
