/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

// SindyByway.h: SindyByway クラスのインターフェイス
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_SINDYBYWAY_H__46C2DF80_6E0A_4FA2_A73D_1FC9B34B9808__INCLUDED_)
#define AFX_SINDYBYWAY_H__46C2DF80_6E0A_4FA2_A73D_1FC9B34B9808__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "SindyLinkQueue.h"

class SindyByway : public SindyLinkQueue  
{
public:
	SindyByway(SindyDBConnection *cDBConnection);
	virtual ~SindyByway();

};

#endif // !defined(AFX_SINDYBYWAY_H__46C2DF80_6E0A_4FA2_A73D_1FC9B34B9808__INCLUDED_)
