/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

// SindyInterNavi.h: SindyInterNavi クラスのインターフェイス
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_SINDYINTERNAVI_H__CFAC1034_8AFC_4E35_8261_576948570D27__INCLUDED_)
#define AFX_SINDYINTERNAVI_H__CFAC1034_8AFC_4E35_8261_576948570D27__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "SindyLinkQueue.h"

class SindyInterNavi : public SindyLinkQueue  
{
public:
	SindyInterNavi(SindyDBConnection *cDBConnection);
	virtual ~SindyInterNavi();

};

#endif // !defined(AFX_SINDYINTERNAVI_H__CFAC1034_8AFC_4E35_8261_576948570D27__INCLUDED_)
