/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

// SindyGuide.h: SindyGuide クラスのインターフェイス
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_SINDYGUIDE_H__EC98BD88_2751_44A6_BFAD_898825BAB9BD__INCLUDED_)
#define AFX_SINDYGUIDE_H__EC98BD88_2751_44A6_BFAD_898825BAB9BD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "SindyLinkQueue.h"

class SindyGuide : public SindyLinkQueue  
{
public:
	SindyGuide(SindyDBConnection *cDBConnection);
	virtual ~SindyGuide();

};

#endif // !defined(AFX_SINDYGUIDE_H__EC98BD88_2751_44A6_BFAD_898825BAB9BD__INCLUDED_)
