/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

// SindyTimeOneway.h: SindyTimeOneway クラスのインターフェイス
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_SINDYTIMEONEWAY_H__0F02DC46_9398_42A2_ABB7_72A6CA1EF384__INCLUDED_)
#define AFX_SINDYTIMEONEWAY_H__0F02DC46_9398_42A2_ABB7_72A6CA1EF384__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "SindyLinkTable.h"

class SindyTimeOneway : public SindyLinkTable  
{
public:
	SindyTimeOneway(SindyDBConnection *cDBConnection);
	virtual ~SindyTimeOneway();

};

#endif // !defined(AFX_SINDYTIMEONEWAY_H__0F02DC46_9398_42A2_ABB7_72A6CA1EF384__INCLUDED_)
