/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

// SindyMiddleMesh.h: SindyMiddleMesh クラスのインターフェイス
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_SINDYMIDDLEMESH_H__B3E20A86_AB0C_4494_A2FE_CFADAB217124__INCLUDED_)
#define AFX_SINDYMIDDLEMESH_H__B3E20A86_AB0C_4494_A2FE_CFADAB217124__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "SindyMeshFeature.h"

class SindyMiddleMesh : public SindyMeshFeature  
{
public:
	SindyMiddleMesh(SindyDBConnection *cDBConnection);
	virtual ~SindyMiddleMesh();

};

#endif // !defined(AFX_SINDYMIDDLEMESH_H__B3E20A86_AB0C_4494_A2FE_CFADAB217124__INCLUDED_)
