/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

// SindyGrad.h: SindyGrad クラスのインターフェイス
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_SINDYGRAD_H__46320C03_251E_4CC1_BB03_041008BF2FDF__INCLUDED_)
#define AFX_SINDYGRAD_H__46320C03_251E_4CC1_BB03_041008BF2FDF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "SindyLineClass.h"

class SindyGrad : public SindyLineClass  
{
public:
	SindyGrad(SindyDBConnection *cDBConnection);
	virtual ~SindyGrad();

};

#endif // !defined(AFX_SINDYGRAD_H__46320C03_251E_4CC1_BB03_041008BF2FDF__INCLUDED_)
