/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

// SindyDupliLink.h: SindyDupliLink クラスのインターフェイス
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_SINDYDUPLILINK_H__A1B67F37_673E_4BF7_9A68_C51864119541__INCLUDED_)
#define AFX_SINDYDUPLILINK_H__A1B67F37_673E_4BF7_9A68_C51864119541__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "SindyLinkTable.h"

class SindyDupliLink : public SindyLinkTable  
{
public:
	SindyDupliLink(SindyDBConnection *cDBConnection);
	virtual ~SindyDupliLink();

};

#endif // !defined(AFX_SINDYDUPLILINK_H__A1B67F37_673E_4BF7_9A68_C51864119541__INCLUDED_)
