/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

// SindyVics.h: SindyVics クラスのインターフェイス
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_SINDYVICS_H__8C968347_4598_4362_87E3_392CCFB4F17D__INCLUDED_)
#define AFX_SINDYVICS_H__8C968347_4598_4362_87E3_392CCFB4F17D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "SindyLinkQueue.h"

class SindyVics : public SindyLinkQueue  
{
public:
	SindyVics(SindyDBConnection *cDBConnection);
	virtual ~SindyVics();

};

#endif // !defined(AFX_SINDYVICS_H__8C968347_4598_4362_87E3_392CCFB4F17D__INCLUDED_)
