//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// LQAttrDirGuideDlg.rc で使用
//
#define IDS_PROJNAME                    101
#define IDS_CAPTION                     102
#define IDS_NAME                        103
#define IDS_CATEGORY                    104
#define IDS_TOOLTIP                     105
#define IDS_MESSAGE                     106
#define IDS_DIRGUIDE                    107
#define IDS_RULEERROR                   108
#define IDS_RULEWORNING                 109
#define IDS_BLANKROW                    110
#define IDS_BLANKCELL                   111
#define IDS_BLANKFIRSTROW               112
#define IDS_DIFFERENTDIRGUIDE           113
#define IDS_SAMESEQUENCE                114
#define IDS_MISTAKESEQUENCE             115
#define IDS_FONT                        116
#define IDS_BLANKKANJI                  117
#define IDC_STATIC_SOURCE               167
#define IDC_EDIT_SOURCE                 177
#define IDC_STATIC_HOUMENYOMI           245
#define IDB_BITMAP_ASEAN_BLUE           272
#define IDB_BITMAP_ASEAN_GREEN          273
#define IDB_BITMAP_ASEAN_ORANGE         275
#define IDB_BITMAP2                     276
#define IDB_BITMAP_ASEAN_WHITE          276
#define IDB_BITMAP_ASEAN_OTHERCOLOR     277
#define IDB_BITMAP_ASEAN_NOTHINGGUIDEPATTERN_C 278
#define IDB_BITMAP_ASEAN_NULL           279
#define IDC_STATIC_HOUMENSHUBETU        382
#define IDC_STATIC_HOUMENKANJI          384
#define IDC_COMBO_SEQUENCE              657
#define IDD_LQATTRDIRGUIDEDLG           763
#define IDC_BUTTON_INS                  769
#define IDC_BUTTON_DEL                  770
#define IDC_BUTTON_UP                   771
#define IDC_BUTTON_DN                   772
#define IDC_STATIC_GROUPBOX_BTN         773
#define IDC_COMBO_INLINKID              781
#define IDC_COMBO_HOUMENSHUBETU1        782
#define IDC_EDIT_HOUMENKANJI1           784
#define IDB_BITMAP_RIGHTTURN            785
#define IDC_EDIT_HOUMENYOMI1            786
#define IDB_BITMAP_LEFTTURN             788
#define IDC_COMBO_HOUMENSHUBETU2        789
#define IDB_BITMAP_STRAIGHT             791
#define IDB_BITMAP_STRAIGHTG            793
#define IDB_BITMAP_RIGHTTURNG           795
#define IDC_COMBO_INNODEID2             797
#define IDB_BITMAP_LEFTTURNG            798
#define IDC_EDIT_HOUMENKANJI2           803
#define IDC_EDIT_HOUMENYOMI2            806
#define IDC_COMBO_HOUMENSHUBETU3        810
#define IDC_EDIT_HOUMENKANJI3           812
#define IDC_EDIT_HOUMENYOMI3            815
#define IDC_COMBO_HOUMENSHUBETU4        819
#define IDC_EDIT_HOUMENKANJI4           822
#define IDC_EDIT_HOUMENYOMI4            825
#define IDC_COMBO_HOUMENSHUBETU5        828
#define IDC_EDIT_HOUMENKANJI5           831
#define IDC_EDIT_HOUMENYOMI5            833
#define IDC_COMBO_HOUMENSHUBETU6        835
#define IDC_EDIT_HOUMENKANJI6           837
#define IDC_EDIT_HOUMENYOMI6            839
#define IDC_COMBO_HOUMENSHUBETU7        841
#define IDC_EDIT_HOUMENKANJI7           843
#define IDC_EDIT_HOUMENYOMI7            845
#define IDC_COMBO_HOUMENSHUBETU8        847
#define IDC_EDIT_HOUMENKANJI8           849
#define IDC_EDIT_HOUMENYOMI8            851
#define IDC_COMBO_HOUMENSHUBETU9        853
#define IDC_EDIT_HOUMENKANJI9           855
#define IDC_EDIT_HOUMENYOMI9            856
#define IDC_COMBO_HOUMENSHUBETU10       857
#define IDC_EDIT_HOUMENKANJI10          859
#define IDC_EDIT_HOUMENYOMI10           860
#define IDC_STATIC_GROUPBOX             862
#define IDC_STATIC_SOURCESEP            894
#define IDC_STATIC_INLINKID             902
#define IDC_STATIC_INNODEID             906
#define IDC_RADIO1                      934
#define IDC_RADIO2                      937
#define IDC_RADIO3                      938
#define IDC_RADIO4                      939
#define IDC_RADIO5                      940
#define IDC_RADIO6                      941
#define IDC_RADIO7                      943
#define IDC_RADIO8                      944
#define IDC_RADIO9                      945
#define IDC_RADIO10                     946
#define IDB_BITMAP_NULL                 1237
#define IDD_DIRGUIDESIGNDLG             1238
#define IDB_BITMAP_NOPATTERN            1239
#define IDB_BITMAP_TWOLEVELCROSSOVERA   1240
#define IDB_BITMAP_TWOLEVELCROSSOVERB   1241
#define IDB_BITMAP_CROSSROADS           1242
#define IDB_BITMAP_LEFTFORKEDROAD       1243
#define IDB_BITMAP_RIGHTFORKEDROAD      1244
#define IDB_BITMAP_YFORKEDROAD          1245
#define IDB_BITMAP_TFORKEDROAD          1246
#define IDB_BITMAP_CROSSROADS0          1247
#define IDB_BITMAP_CROSSROADS1          1248
#define IDB_BITMAP_CROSSROADS2          1249
#define IDB_BITMAP_LEFTFORKEDROAD0      1250
#define IDB_BITMAP_LEFTFORKEDROAD1      1251
#define IDB_BITMAP_RIGHTFORKEDROAD0     1252
#define IDB_BITMAP_RIGHTFORKEDROAD1     1253
#define IDB_BITMAP_TFORKEDROAD0         1254
#define IDB_BITMAP_TFORKEDROAD1         1255
#define IDB_BITMAP_TWOLEVELCROSSOVERA0  1256
#define IDB_BITMAP_TWOLEVELCROSSOVERA1  1257
#define IDB_BITMAP_TWOLEVELCROSSOVERA2  1258
#define IDB_BITMAP_TWOLEVELCROSSOVERB0  1259
#define IDB_BITMAP_TWOLEVELCROSSOVERB1  1260
#define IDB_BITMAP_TWOLEVELCROSSOVERB2  1261
#define IDB_BITMAP_YFORKEDROAD0         1262
#define IDB_BITMAP_YFORKEDROAD1         1263
#define IDB_BITMAP_NOTHINGGUIDEPATTERN_C 1265
#define IDC_STATIC_SEQENCE              1674

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        280
#define _APS_NEXT_COMMAND_VALUE         32769
#define _APS_NEXT_CONTROL_VALUE         774
#define _APS_NEXT_SYMED_VALUE           305
#endif
#endif
