/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

// This file was generated by WTL Dialog wizard 
// ConnectDlg.h : Declaration of the CConnectDlg

#pragma once

#include "resource.h"       // main symbols
#include <atlddx.h>
#include <atlframe.h>
// CConnectDlg

enum WorkspaceVersion{
	VER_DEFAULT,
	VER_SRC,
	VER_DST
};

class CConnectDlg : 
	public CDialogImpl<CConnectDlg>,
	public CWinDataExchange<CConnectDlg>,
	public CDialogResize<CConnectDlg>	
{

public:
	CConnectDlg();
	~CConnectDlg();
	enum { IDD = IDD_DIALOG1 };

    BEGIN_MSG_MAP(CConnectDlg)
		MESSAGE_HANDLER(WM_INITDIALOG, OnInitDialog)
        COMMAND_HANDLER(IDOK, BN_CLICKED, OnClickedOK)
        COMMAND_HANDLER(IDCANCEL, BN_CLICKED, OnClickedCancel)
        COMMAND_HANDLER(IDC_BUTTON_FILESELECT, BN_CLICKED, OnClickedFileSelect)
		COMMAND_HANDLER_EX(IDC_EDIT_USERNAME, EN_CHANGE, OnChangeUsername)
		CHAIN_MSG_MAP(CDialogResize<CConnectDlg>)
    END_MSG_MAP()

	BEGIN_DDX_MAP(CConnectDlg)
		DDX_TEXT(IDC_EDIT_SERVERNAME, m_strServername)
		DDX_TEXT(IDC_EDIT_USERNAME, m_strUsername)
		DDX_TEXT(IDC_EDIT_PASSWORD, m_strPassword)
		DDX_TEXT(IDC_EDIT_SRCCSV, m_strSrccsv)
		DDX_TEXT(IDC_EDIT_DESTFEATURECLASS, m_strDestfeatureclass)
	END_DDX_MAP()

	BEGIN_DLGRESIZE_MAP(CConnectDlg)
		DLGRESIZE_CONTROL(IDC_EDIT_SERVERNAME, DLSZ_SIZE_X)
		DLGRESIZE_CONTROL(IDC_EDIT_USERNAME, DLSZ_MOVE_X)
	END_DLGRESIZE_MAP()


    // Handler prototypes:
    //  LRESULT MessageHandler(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
    //  LRESULT CommandHandler(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
    //  LRESULT NotifyHandler(int idCtrl, LPNMHDR pnmh, BOOL& bHandled);
	LRESULT OnInitDialog(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled);
	LRESULT OnClickedOK(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnClickedCancel(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	LRESULT OnClickedFileSelect(WORD wNotifyCode, WORD wID, HWND hWndCtl, BOOL& bHandled);
	
public:
	// 更新元と更新先のワークスペースを準備する
	bool Connect( LPCTSTR strNewVerName );

	// ワークスペース取得用関数
	IWorkspacePtr GetWorkspace( WorkspaceVersion enumWhatVersion );

	// CSVファイルパス取得関数
	CString GetCSVPath(){ return m_strSrccsv; }

	bool IsVersioned(){ return m_bIsVersioned; }

	CString DestFeatureClassName(){ return m_strDestfeatureclass; }

private:
	// サーバに接続してワークスペースを開く
	IWorkspacePtr OpenWorkSpace( LPCTSTR strVersionName );

protected:
	CString			m_strServername,		//!< 接続サーバ名
					m_strUsername,			//!< 接続ユーザ名
					m_strPassword,			//!< パスワード
					m_strSrccsv,			//!< 更新元csvファイル
					m_strDestfeatureclass;  //!< 更新先フィーチャクラス

	IWorkspacePtr	m_ipDefaultWorkSpace,	//!< SDE.DEFAULTのワークスペース
					m_ipSrcWorkSpace,		//!< 更新元バージョンのワークスペース
					m_ipDstWorkSpace;		//!< 更新先バージョンのワークスペース

	bool			m_bIsVersioned;			//!< 更新先はバージョン対応レイヤ？

public:
	LRESULT OnChangeUsername(WORD wNotifyCode, WORD wID, HWND hWndCtl);
};


