/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

#pragma once

#include "stdafx.h"
#include "resource.h"

// [SiNDYChildDlg] ウィンドウマネージャ配置マップ
BEGIN_WINDOW_MAP(LANE_NODE_MAP)
	BEGINROWS(WRCT_REST,0,RCMARGINS(2,2))
		BEGINROWS(WRCT_PCT,0,90)
			BEGINROWS(WRCT_REST, IDC_STATIC_BASE_GROUP, RCMARGINS(10,10))
				RCSPACE(10)
				//基本情報
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10,0))
					RCTOFIT(IDC_STATIC_NODECLASS_C)
					RCTOFIT(-1)
					RCSPACE(3)
					RCREST(IDC_COMBO_NODECLASS_C)	
				ENDGROUP()
				RCSPACE(3)
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10,0))
					RCTOFIT(IDC_STATIC_POSITION_C)
					RCTOFIT(-1)
					RCSPACE(3)
					RCREST(IDC_COMBO_POSITION_C)	
				ENDGROUP()
				RCSPACE(3)
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10,0))
					RCTOFIT(IDC_CHECK_STOP_POINT_F)
				ENDGROUP()
				RCSPACE(3)
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10,0))
					RCTOFIT(IDC_CHECK_COVERING_F)
				ENDGROUP()
				RCSPACE(5)
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10,0))
					RCTOFIT(IDC_STATIC_NQ_INFO)
				ENDGROUP()
				RCSPACE(3)
				BEGINCOLS(WRCT_REST, 0, RCMARGINS(10,0))
					RCREST(IDC_GRID_NQ)
				ENDGROUP()
			ENDGROUP()
			BEGINROWS(WRCT_TOFIT, IDC_STATIC_EXTENSION_GROUP, RCMARGINS(10,10))
				RCSPACE(10)
				//拡張情報
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10,0))
					RCTOFIT(IDC_STATIC_SPECULATION_C)
					RCTOFIT(-1)
					RCSPACE(3)
					RCREST(IDC_COMBO_SPECULATION_C)
				ENDGROUP()
				RCSPACE(3)
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10,0))
					RCTOFIT(IDC_STATIC_SOURCE_ID)
					RCTOFIT(-1)
					RCSPACE(3)
					RCREST(IDC_EDIT_SOURCE_ID)
				ENDGROUP()
			ENDGROUP()
		ENDGROUP()
		//情報ソース
		BEGINROWS(WRCT_PCT, 0, 10)
			RCSPACE(3)
			BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10,0))
				RCREST(IDC_STATIC_VAR)
			ENDGROUP()
			RCSPACE(3)
			BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10,0))
				RCTOFIT(IDC_STATIC_SOURCE)
				RCTOFIT(-1)
				RCREST(IDC_EDIT_SOURCE)
			ENDGROUP()
		ENDGROUP()
	ENDGROUP()
END_WINDOW_MAP()

