/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/


#if !defined(AFX_CHECKACCESSROAD_H__31FD2137_1A0F_4EC2_BB9A_1700BDE83A70__INCLUDED_)
#define AFX_CHECKACCESSROAD_H__31FD2137_1A0F_4EC2_BB9A_1700BDE83A70__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "resource.h"
#include "App.h"

#endif // !defined(AFX_CHECKACCESSROAD_H__31FD2137_1A0F_4EC2_BB9A_1700BDE83A70__INCLUDED_)
