/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// AttrRoadmarkAreaDlg.rc で使用
//
#define IDD_ROADMARKAREADLG             101
#define IDR_MENU_GRID                   103
#define IDS_ERR_RELATION_NODE           104
#define IDS_ERR_RELATION_LINK           104
#define IDS_ERR_INVALID_VALUE_IN_GRID   105
#define IDC_STATIC_SOURCE               167
#define IDC_EDIT_SOURCE                 177
#define IDC_STATIC_BAR                  692
#define IDC_STATIC_DESCRIPTION          1001
#define IDC_EDIT_DESCRIPTION            1002
#define IDC_VSFLEXGRID_LANE_LINK        1004
#define IDC_STATIC_ROADMARK_C           1005
#define IDC_EDIT_SOURCE_ID              1009
#define IDC_STATIC_SOURCE_ID            1050
#define ID_MENUITEM_DELETE              40003
#define IDC_STATIC_REL_LANE_LINK        40003
#define ID_MENUITEM_ADD                 40004
#define IDC_STATIC_SPECULATION_C        40004
#define IDC_COMBO_SPECULATION_C         40014
#define IDC_COMBO_ROADMARK_C            40015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
