/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

// KKDRecord.h: KKDRecord クラスのインターフェイス
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_KKDRECORD_H__62A7CECB_6080_41FD_99F8_83CAF1696EFD__INCLUDED_)
#define AFX_KKDRECORD_H__62A7CECB_6080_41FD_99F8_83CAF1696EFD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include <DRMAValues.h>
#include <DRMARecord.h>
#include "KKDValues.h"

/**
 * @brief KKDレコードクラス
 */
template<typename TFormat>
class KKDRecordT : public DRMARecordT<TFormat>
{
};

#endif // !defined(AFX_KKDRECORD_H__62A7CECB_6080_41FD_99F8_83CAF1696EFD__INCLUDED_)
