//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// AttrRoadLinkDlg.rc で使用
//
#define IDS_PROJNAME                    101
#define IDS_CAPTION                     102
#define IDC_GRID_NOPASSAGE              103
#define IDS_NAME                        103
#define IDC_GRID_ONEWAY                 104
#define IDS_CATEGORY                    104
#define IDS_TOOLTIP                     105
#define IDC_STATIC_MANAGER              106
#define IDS_MESSAGE                     106
#define IDC_STATIC_DISPCLASS            107
#define IDS_BASE                        107
#define IDC_STATIC_NAVICLASS            108
#define IDS_EXTENTION                   108
#define IDS_REGULATION                  109
#define IDC_STATIC_LEFTCHANGE           110
#define IDS_NUMBER                      110
#define IDC_CHECK_BYPASS                111
#define IDS_DRMA                        111
#define IDC_STATIC_LINKCLASS            112
#define IDS_PARKING                     112
#define IDC_CHECK_ISLANDF               113
#define IDS_NOROADCODELIST              113
#define IDS_OUTOFWORKYEARRANGE          114
#define IDC_COMBO_MANAGER               115
#define IDS_VICSERROR                   115
#define IDS_RELATIONERROR               116
#define IDS_RELATIONWORNING             117
#define IDC_STATIC_ROADWIDTH            118
#define IDS_FAILTOSEARCH                118
#define IDS_INVALIDROADNO               119
#define IDS_ERRORANDWORNING             120
#define IDC_COMBO_ROADWIDTH             121
#define IDS_WHENROADCLASS               121
#define IDC_COMBO_DISPCLASS             122
#define IDS_NAVICLASSISERROR            122
#define IDC_COMBO_NAVICLASS             123
#define IDS_NAVICLASSISWORNING          123
#define IDC_COMBO_ONEWAY_C              124
#define IDS_ERROR1                      124
#define IDS_ERROR2                      125
#define IDC_COMBO_LINKCLASS1            126
#define IDS_WORNING1                    126
#define IDC_STATIC_LANE                 127
#define IDS_WORNING2                    127
#define IDC_COMBO_UPDOWNC               128
#define IDS_ASCENDING                   128
#define IDC_STATIC_RIGHTCHANGE          129
#define IDS_DESCENDING                  129
#define IDS_NOPREFCODELIST              130
#define IDC_COMBO_ALLEYMAINTE           131
#define IDS_NOSECTIONCODELIST           131
#define IDC_STATIC_UPDOWNC              132
#define IDS_CANTSPECIFIEDPREFCODE       132
#define IDC_CHECK_CARONLYF              133
#define IDS_NONAME                      133
#define IDS_PREFROADNAME                134
#define IDC_CHECK_LANE                  135
#define IDS_NAMEKANJI                   135
#define IDS_DISPKANJI                   136
#define IDC_EDIT_LEFTCHANGE             137
#define IDS_SHIELDNUMBER                137
#define IDC_EDIT_RIGHTCHANGE            138
#define IDS_SECTIONNAME                 138
#define IDC_STATIC_WIDEAREA             139
#define IDS_PREFNAME                    139
#define IDC_COMBO_WIDEAREA              140
#define IDS_OUTOFROADCODERANGE          140
#define IDC_STATIC_REGULERONEWAY        141
#define IDS_OUTOFPREFCODERANGE          141
#define IDC_COMBO_ONEWAY                142
#define IDS_OUTOFROADNORANGE            142
#define IDC_STATIC_REGULERNOPASSAGE     143
#define IDS_OUTOFSECTIONCODERANGE       143
#define IDC_COMBO_NOPASSAGE             144
#define IDS_FAILTOSEARCHROADNO          144
#define IDC_STATIC_LEGALSPEED           145
#define IDS_FAILTOSEARCHSECTIONCODE     145
#define IDC_COMBO_LEGALSPEED            146
#define IDS_NONAMEWARNING               146
#define IDC_STATIC_ROADCODE             147
#define IDS_CANTSPECIFIEDROADNO         147
#define IDC_EDIT_ROADCODE               148
#define IDS_BEYONDPREFBORDER            148
#define IDC_BUTTON_SEARCHROADCODE       149
#define IDS_NOCITYADMIN                 149
#define IDC_STATIC_NAMEKANJI            150
#define IDC_STATIC_KANJINAME2           151
#define IDC_STATIC_WALKABLE             152
#define IDC_COMBO_WALKABLE              153
#define IDC_STATIC_ROADNUMBER           156
#define IDC_STATIC_KUBUNCODE            158
#define IDC_STATIC_TRIPSPEED            159
#define IDC_STATIC_LIMITSPEED           160
#define IDC_COMBO_KUBUNCODE             161
#define IDC_EDIT_TRIPSPEED              162
#define IDC_COMBO_LIMITSPEED            163
#define IDC_STATIC_SOURCE               167
#define IDC_EDIT_SOURCE                 177
#define IDC_EDIT_ROADNUMBER             184
#define IDC_STATIC_ROADNUMBER2          188
#define IDC_EDIT_LANE                   234
#define IDC_STATIC_ONEWAYGROUP          299
#define IDC_STATIC_NOPASSAGEGROUP       300
#define IDC_STATIC_ALLEYCODE            349
#define IDC_STATIC_PARKINGCLASS         488
#define IDC_COMBO_PARKINGCLASS          491
#define IDC_STATIC_PARKINGLINKCLASS     494
#define IDC_COMBO_PARKINGLINKCLASS      496
#define IDC_STATIC_FLOORLEVEL           499
#define IDC_EDIT_FLOORLEVEL             502
#define IDC_STATIC_MIDDLEFLOOR_LEVEL    687
#define IDC_EDIT_MIDDLEFLOOR_LEVEL      688
#define IDC_STATIC_WORKYEAR             716
#define IDC_EDIT_WORKYEAR               717
#define IDC_TAB_ROADATTR                746
#define IDC_CHECK_WIDEAREAF             769
#define IDC_COMBO_BATCHCHANGE           770
#define IDC_STATIC_BATCHCHANGE          771
#define IDC_STATIC_PREFCODE             774
#define IDC_EDIT_PREFCODE               775
#define IDC_BUTTON_SEARCHPREFCODE       776
#define IDC_STATIC_PREFNAME             777
#define IDC_STATIC_PREFNAME2            778
#define IDC_STATIC_PREFCODENAME         779
#define IDC_STATIC_PREFROADNAME         779
#define IDC_STATIC_PREFCODENAME2        780
#define IDC_STATIC_DISPLAYKANJI         781
#define IDC_STATIC_DISPLAYKANJI2        782
#define IDC_STATIC_SHIELDNUMBER         783
#define IDC_STATIC_SHIELDNUMBER2        784
#define IDC_STATIC_SECTIONCODE          785
#define IDC_EDIT_SECTIONCODE            786
#define IDC_BUTTON_SEARCHSECTIONCODE    787
#define IDC_BUTTON_SEARCHROADNUMBER     788
#define IDC_STATIC_SECTIONNAME          789
#define IDC_STATIC_SECTIONNAME2         790
#define IDC_STATIC_HIGHWAYNUMBER        791
#define IDC_EDIT_HIGHWAYNUMBER          792
#define IDC_STATIC_NAMEKANJI2           793
#define IDC_EDIT_NAMEKANJI              794
#define IDC_EDIT_DISPLAYKANJI           795
#define IDC_EDIT_SHIELDNUMBER           796
#define IDC_EDIT_PREFNAME               797
#define IDC_EDIT_PREFROADNAME           798
#define IDC_EDIT_SECTIONNAME            799
#define IDC_EDIT1                       800
#define IDC_STATIC_BAR                  801
#define IDC_STATIC_BAR2                 802
#define IDC_STATIC_BAR3                 803
#define IDC_EDIT9                       815
#define IDD_ATTRROADLINKDLG             10030

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        274
#define _APS_NEXT_COMMAND_VALUE         32769
#define _APS_NEXT_CONTROL_VALUE         816
#define _APS_NEXT_SYMED_VALUE           305
#endif
#endif
