/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

#define TAG_ERROR "#ERROR"
#define TAG_INFO "#INFO"

#define MESSAGE_NOT_FIXED_VALUE _T ("固定値ではありません")
#define MESSAGE_NOT_EQUALS_VALUE _T("比較先と値が異なります")
#define MESSAGE_IS_NULL _T("値が格納されていません")
#define MESSAGE_IS_NOT_NULL _T("値が格納されています")
#define MESSAGE_CAN_NOT_GET_FIELDINDEX _T("フィールドインデックスを取得できません")
#define MESSAGE_CAN_NOT_GET_VALUE _T("値を取得できません")

