//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// LQAttrLaneDlg.rc で使用
//
#define IDS_PROJNAME                    101
#define IDS_CAPTION                     102
#define IDS_NAME                        103
#define IDS_CATEGORY                    104
#define IDS_TOOLTIP                     105
#define IDS_MESSAGE                     106
#define IDS_DIRGUIDE                    107
#define IDS_LANE                        107
#define IDS_INCONSISTENTDATA            108
#define IDS_NOCHECK                     109
#define IDS_EXCEPTNUMBEROFLANEAPP       110
#define IDS_EXCEPTNUMBEROFRIGHTLANE     111
#define IDS_EXCEPTNUMBEROFLEFTLANE      112
#define IDS_RETURNVALUE                 113
#define IDS_CORRECTVALUE                114
#define IDS_FONT                        115
#define IDC_STATIC_SOURCE               167
#define IDC_EDIT_SOURCE                 177
#define IDB_BITMAP_GRIDMODE             216
#define IDB_BITMAP_ALIASMODE            218
#define IDB_BITMAP_DBNAMEMODE           220
#define IDB_BITMAP_COMMONMODE           222
#define IDB_BITMAP_PATTERN_A            275
#define IDB_BITMAP_PATTERN_F            276
#define IDB_BITMAP_PATTERN_B            277
#define IDB_BITMAP_PATTERN_C            278
#define IDB_BITMAP_PATTERN_D            279
#define IDB_BITMAP_PATTERN_E            280
#define IDB_BITMAP_PATTERN_A_DISABLED   283
#define IDB_BITMAP_PATTERN_F_DISABLED   284
#define IDB_BITMAP_PATTERN_B_DISABLED   285
#define IDB_BITMAP_PATTERN_C_DISABLED   286
#define IDB_BITMAP_PATTERN_D_DISABLED   287
#define IDB_BITMAP_PATTERN_E_DISABLED   288
#define IDB_BITMAP_DIR_0                295
#define IDB_BITMAP_DIR_45               296
#define IDB_BITMAP_DIR_90               297
#define IDB_BITMAP_DIR_135              298
#define IDB_BITMAP_DIR_180              299
#define IDB_BITMAP_DIR_225              300
#define IDB_BITMAP_DIR_270              301
#define IDB_BITMAP_DIR_315              302
#define IDB_BITMAP_DIR_NULL             303
#define IDB_BITMAP_DIR_WORKING          304
#define IDC_STATIC_DIRECTION            573
#define IDS_CANTSETLANEPASS             758
#define IDS_CANTGETCURRENTFEATURE       762
#define IDD_LQATTRLANEDLG               766
#define IDC_BUTTON_PATTERN_A            769
#define IDC_BUTTON_PATTERN_B            771
#define IDC_BUTTON_PATTERN_C            776
#define IDC_BUTTON_PATTERN_D            777
#define IDC_BUTTON_PATTERN_E            778
#define IDC_BUTTON_PATTERN_F            779
#define IDC_COMBO_INLINKID              781
#define IDC_COMBO_INNODEID              783
#define IDB_BITMAP_RIGHTTURN            785
#define IDC_STATIC_SEP                  787
#define IDB_BITMAP_LEFTTURN             788
#define IDB_BITMAP_STRAIGHT             791
#define IDC_STATIC_SEP2                 792
#define IDB_BITMAP_STRAIGHTG            793
#define IDB_BITMAP_RIGHTTURNG           795
#define IDC_BUTTON_L1R0                 796
#define IDB_BITMAP_LEFTTURNG            798
#define IDC_BUTTON_L0R1                 799
#define IDC_BUTTON_L0R0                 801
#define IDB_BITMAP_DONTGO               802
#define IDB_BITMAP_CMNGO                804
#define IDC_STATIC_LANESTATE            805
#define IDB_BITMAP_SHITEIGO             807
#define IDC_BUTTON_AUTODIR              809
#define IDC_BUTTON_1xx0                 811
#define IDC_BUTTON_0xx1                 813
#define IDB_BITMAP_LANE                 816
#define IDC_BUTTON_0xx0                 817
#define IDB_BITMAP_MINISTRAIGHT         821
#define IDB_BITMAP_LANERMASK            823
#define IDB_BITMAP_DIRECTION            827
#define IDB_BITMAP_SELECTOR             830
#define IDB_BITMAP_MINISHITEIGO         832
#define IDB_BITMAP_MINIDONTGO           834
#define IDB_BITMAP_DIRECTIONSW          838
#define IDB_BITMAP_DIRECTIONW           840
#define IDB_BITMAP_DIRECTIONNW          842
#define IDB_BITMAP_DIRECTIONN           844
#define IDB_BITMAP_DIRECTIONNE          846
#define IDB_BITMAP_DIRECTIONE           848
#define IDB_BITMAP_DIRECTIONSE          850
#define IDB_BITMAP_DIRECTIONS           852
#define IDB_BITMAP_DIRECTIONNULL        853
#define IDB_BITMAP_MINIGRAY1            854
#define IDC_SPIN_LANEAPP                884
#define IDC_STATIC_LANERCHANGE          887
#define IDC_STATIC_LANECLASS            888
#define IDC_STATIC_LANEAPP              889
#define IDC_EDIT_LANEAPP                891
#define IDC_EDIT_LANERCHANGE            892
#define IDC_STATIC_LANELCHANGE          895
#define IDC_EDIT_LANELCHANGE            897
#define IDC_STATIC_LANEPASS             899
#define IDC_EDIT_LANEPASS               900
#define IDC_STATIC_PATTERN              901
#define IDC_STATIC_INLINKID             902
#define IDC_STATIC_LANECHANGE           904
#define IDC_STATIC_INNODEID             906
#define IDC_SPIN_LANELCHANGE            908
#define IDC_SPIN_LANERCHANGE            909
#define IDC_STATIC_LANEFLOW2            911
#define IDC_EDIT_LANEFLOW2              913
#define IDC_BUTTON_DIR_WORKING          920
#define IDC_BUTTON_DIR_0                921
#define IDC_BUTTON_DIR_45               922
#define IDC_BUTTON_DIR_90               923
#define IDC_BUTTON_DIR_135              924
#define IDC_BUTTON_DIR_180              925
#define IDC_BUTTON_DIR_225              926
#define IDC_BUTTON_DIR_270              927
#define IDC_BUTTON_DIR_315              928
#define IDC_BUTTON_DIR_NULL             929

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        296
#define _APS_NEXT_COMMAND_VALUE         32769
#define _APS_NEXT_CONTROL_VALUE         774
#define _APS_NEXT_SYMED_VALUE           305
#endif
#endif
