/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

#pragma once
#include "ErrLog.h"
//フィールド名等の固定文字列

//メンテリストフィールド名
extern LPCTSTR MAINTE_FIELD_LINE_NO;
extern LPCTSTR MAINTE_FIELD_VARID_DATE;
extern LPCTSTR MAINTE_FIELD_DELETE_CODE;
extern LPCTSTR MAINTE_FIELD_CLOSED_CODE;
extern LPCTSTR MAINTE_FIELD_CLOSED_MEMO;
extern LPCTSTR MAINTE_FIELD_INTRO;
extern LPCTSTR MAINTE_FIELD_INTRO_DOT;
extern LPCTSTR MAINTE_FIELD_XML;
extern LPCTSTR MAINTE_FIELD_XML_PARKING;
extern LPCTSTR MAINTE_FIELD_XML_ARRIVAL;
extern LPCTSTR MAINTE_FIELD_SEQUENCE;
extern LPCTSTR MAINTE_FIELD_BANK_SEQUENCE;
extern LPCTSTR MAINTE_FIELD_FUNC_SEQ;
extern LPCTSTR MAINTE_FIELD_GS_SEQUENCE;
extern LPCTSTR MAINTE_FIELD_PREFNAME;
extern LPCTSTR MAINTE_FIELD_CITY_NAME;
extern LPCTSTR MAINTE_FIELD_ADDR;
extern LPCTSTR MAINTE_FIELD_LONG256;
extern LPCTSTR MAINTE_FIELD_LAT256;
extern LPCTSTR MAINTE_FIELD_ROOT_LONG256;
extern LPCTSTR MAINTE_FIELD_ROOT_LAT256;
extern LPCTSTR MAINTE_FIELD_LONG_DEG;
extern LPCTSTR MAINTE_FIELD_LAT_DEG;
extern LPCTSTR MAINTE_FIELD_LONG;
extern LPCTSTR MAINTE_FIELD_LAT;
extern LPCTSTR MAINTE_FIELD_CONTENTS_NAME;
extern LPCTSTR MAINTE_FIELD_MOD_CONTENTS_NAME;
extern LPCTSTR MAINTE_FIELD_INFOFILE_ID;
extern LPCTSTR MAINTE_FIELD_EXIST_INFOFILE;
extern LPCTSTR MAINTE_FIELD_YOMI;
extern LPCTSTR MAINTE_FIELD_NAME;
extern LPCTSTR MAINTE_FIELD_PRECISION;
extern LPCTSTR MAINTE_FIELD_COMPANY;
extern LPCTSTR MAINTE_FIELD_LANDMARK;
extern LPCTSTR MAINTE_FIELD_WORK_MEMO;
extern LPCTSTR MAINTE_FIELD_ADMIN_MEMO;
extern LPCTSTR MAINTE_FIELD_BG_INFO1;
extern LPCTSTR MAINTE_FIELD_BG_INFO2;
extern LPCTSTR MAINTE_FIELD_URL;
extern LPCTSTR MAINTE_FIELD_TEL;
extern LPCTSTR MAINTE_FIELD_USE_ID;
extern LPCTSTR MAINTE_FIELD_PERIOD;
extern LPCTSTR MAINTE_FIELD_PIC;
extern LPCTSTR MAINTE_FIELD_LIQUOR_FLAG;
extern LPCTSTR MAINTE_FIELD_CIGAR_FLAG;
extern LPCTSTR MAINTE_FIELD_TOOLROAD_FLAG;

//銀行ATM向け特別
extern LPCTSTR MAINTE_FIELD_WINDOW;
extern LPCTSTR MAINTE_FIELD_ATM;
extern LPCTSTR MAINTE_FIELD_BANK_DELETE_FLAG;
extern LPCTSTR MAINTE_FIELD_BABK_CLOSED_CODE;
extern LPCTSTR MAINTE_FIELD_BANK_CLOSED_MEMO;
extern LPCTSTR MAINTE_FIELD_BANK_PARKING;
extern LPCTSTR MAINTE_FIELD_BANK_BIS_TIME;
extern LPCTSTR MAINTE_FIELD_BANK_BIS_HOLIDAY;
extern LPCTSTR MAINTE_FIELD_FORM;

extern LPCTSTR MAINTE_FIELD_NOT_CHECK1;
extern LPCTSTR MAINTE_FIELD_NOT_CHECK2;
extern LPCTSTR MAINTE_FIELD_NOT_CHECK3;
extern LPCTSTR MAINTE_FIELD_NOT_CHECK4;
extern LPCTSTR MAINTE_FIELD_NOT_CHECK5;
extern LPCTSTR MAINTE_FIELD_NOT_CHECK6;

extern LPCTSTR MAINTE_FIELD_ROOT_PRI;
extern LPCTSTR MAINTE_FIELD_ROOT_PRI_ATTR;
extern LPCTSTR MAINTE_FIELD_ROOT_ATTR;
extern LPCTSTR MAINTE_FIELD_ROOT_DELCODE;

extern LPCTSTR MAINTE_FIELD_ROOT_POINT;
extern LPCTSTR MAINTE_FIELD_MODIFY;

// 1/256秒を度にする係数(3600*256)
extern const DOUBLE DIV_256_TO_DEG;
