/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

#include "StdAfx.h"
#include "Defines.h"

//フィールド名等の固定文字列
//メンテリストフィールド名
LPCTSTR MAINTE_FIELD_LINE_NO = _T("行番号");
LPCTSTR MAINTE_FIELD_VARID_DATE = _T("更新情報有効日付");
LPCTSTR MAINTE_FIELD_DELETE_CODE = _T("削除コード");
LPCTSTR MAINTE_FIELD_CLOSED_CODE = _T("閉鎖理由コード");
LPCTSTR MAINTE_FIELD_CLOSED_MEMO = _T("閉鎖理由メモ");
LPCTSTR MAINTE_FIELD_INTRO = _T("紹介文");
LPCTSTR MAINTE_FIELD_INTRO_DOT = _T("紹介文.");
LPCTSTR MAINTE_FIELD_XML = _T("整備作業情報（XML）.");
LPCTSTR MAINTE_FIELD_XML_PARKING = _T("駐車場ポイント整備作業情報");
LPCTSTR MAINTE_FIELD_XML_ARRIVAL = _T("到達ポイント整備作業情報");
LPCTSTR MAINTE_FIELD_SEQUENCE = _T("シーケンス");
LPCTSTR MAINTE_FIELD_BANK_SEQUENCE = _T("窓口・ATMシーケンス");

LPCTSTR MAINTE_FIELD_FUNC_SEQ = _T("機能内シーケンス");
LPCTSTR MAINTE_FIELD_GS_SEQUENCE = _T("POI識別子");

LPCTSTR MAINTE_FIELD_PREFNAME = _T("都道府県");
LPCTSTR MAINTE_FIELD_CITY_NAME = _T("市区町村");
LPCTSTR MAINTE_FIELD_ADDR = _T("住所");
LPCTSTR MAINTE_FIELD_LONG256 = _T("1/256経度");
LPCTSTR MAINTE_FIELD_LAT256 = _T("1/256緯度");
LPCTSTR MAINTE_FIELD_LONG_DEG = _T("度分秒経度");
LPCTSTR MAINTE_FIELD_LAT_DEG = _T("度分秒緯度");
LPCTSTR MAINTE_FIELD_LONG = _T("経度");
LPCTSTR MAINTE_FIELD_LAT = _T("緯度");
LPCTSTR MAINTE_FIELD_CONTENTS_NAME = _T("コンテンツ名称");
LPCTSTR MAINTE_FIELD_MOD_CONTENTS_NAME = _T("コンテンツ名称（修正）");
LPCTSTR MAINTE_FIELD_INFOFILE_ID = _T("情報ファイルID");
LPCTSTR MAINTE_FIELD_EXIST_INFOFILE = _T("検索画像有無");
LPCTSTR MAINTE_FIELD_YOMI = _T("読み");
LPCTSTR MAINTE_FIELD_NAME = _T("名称");
LPCTSTR MAINTE_FIELD_PRECISION = _T("精度");
LPCTSTR MAINTE_FIELD_COMPANY = _T("座標値提供元コード");
LPCTSTR MAINTE_FIELD_LANDMARK = _T("ランドマーク");
LPCTSTR MAINTE_FIELD_WORK_MEMO = _T("作業者メモ");
LPCTSTR MAINTE_FIELD_ADMIN_MEMO = _T("管理者メモ");
LPCTSTR MAINTE_FIELD_BG_INFO1 = _T("参考資料1");
LPCTSTR MAINTE_FIELD_BG_INFO2 = _T("参考資料2");
LPCTSTR MAINTE_FIELD_URL = _T("URL");
LPCTSTR MAINTE_FIELD_TEL = _T("電話番号");
LPCTSTR MAINTE_FIELD_USE_ID = _T("情報提供元利用ID");
LPCTSTR MAINTE_FIELD_PERIOD = _T("指定期間");
LPCTSTR MAINTE_FIELD_PIC = _T("その他情報");
LPCTSTR MAINTE_FIELD_LIQUOR_FLAG = _T("お酒販売");
LPCTSTR MAINTE_FIELD_CIGAR_FLAG = _T("ﾀﾊﾞｺ販売");
LPCTSTR MAINTE_FIELD_TOOLROAD_FLAG = _T("有料道路フラグ");

//銀行ATM向け特別
LPCTSTR MAINTE_FIELD_WINDOW = _T("窓口_");
LPCTSTR MAINTE_FIELD_ATM = _T("ATM_");
LPCTSTR MAINTE_FIELD_BANK_DELETE_FLAG = _T("削除フラグ");
LPCTSTR MAINTE_FIELD_BABK_CLOSED_CODE = _T("閉鎖理由コード");
LPCTSTR MAINTE_FIELD_BANK_CLOSED_MEMO = _T("閉鎖日付・理由");
LPCTSTR MAINTE_FIELD_BANK_PARKING = _T("駐車場");
LPCTSTR MAINTE_FIELD_BANK_BIS_TIME = _T("営業時間");
LPCTSTR MAINTE_FIELD_BANK_BIS_HOLIDAY = _T("休業日");
LPCTSTR MAINTE_FIELD_FORM = _T("店舗形態種別");


//「（修正）」がなくても元値として扱わない
LPCTSTR MAINTE_FIELD_NOT_CHECK1 = _T("差分取得備考");
LPCTSTR MAINTE_FIELD_NOT_CHECK2 = _T("座標値確認フラグ");
LPCTSTR MAINTE_FIELD_NOT_CHECK3 = _T("調査対象フラグ");
LPCTSTR MAINTE_FIELD_NOT_CHECK4 = _T("調査者名");
LPCTSTR MAINTE_FIELD_NOT_CHECK5 = _T("調査結果フラグ");
LPCTSTR MAINTE_FIELD_NOT_CHECK6 = _T("備考欄");

LPCTSTR MAINTE_FIELD_ROOT_LONG256 = _T("ルート探索用ポイント.1/256経度");
LPCTSTR MAINTE_FIELD_ROOT_LAT256 = _T("ルート探索用ポイント.1/256緯度");
LPCTSTR MAINTE_FIELD_ROOT_PRI = _T("座標値種別内優先順位");
LPCTSTR MAINTE_FIELD_ROOT_PRI_ATTR = _T("座標値種別内優先順位種別コード");
LPCTSTR MAINTE_FIELD_ROOT_ATTR = _T("座標値種別コード");

LPCTSTR MAINTE_FIELD_ROOT_DELCODE = _T("ルート探索用ポイント.削除コード");

LPCTSTR MAINTE_FIELD_ROOT_POINT = _T("ルート探索用ポイント.");
LPCTSTR MAINTE_FIELD_MODIFY = _T("（修正）");

// 1/256秒を度にする係数(3600*256)
const DOUBLE DIV_256_TO_DEG = 921600.0;

