//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SiNDYLib.rc
//
#define IDS_SINDYERR_NOERR              1
#define IDS_SINDYERR_ARGISNULL          2
#define IDS_SINDYERR_ARGINCONSISTENCY   3
#define IDS_SINDYERR_COMINTERFACEISNULL 4
#define IDS_SINDYERR_COMFUNCTIONFAILED  5
#define IDS_SINDYERR_AOSTOREFAILED      6
#define IDS_SINDYERR_AOGETVALUEFAILED   7
#define IDS_SINDYERR_AOPUTVALUEFAILED   8
#define IDS_SINDYERR_ANNOSTRLENNOTSAME  9
#define IDS_SINDYERR_ANNOSTRISNOTHALFNUMBER 10
#define IDS_SINDYERR_ANNOSTRISHALFZERO  11
#define IDS_SINDYERR_ANNOSTRISNOTWIDE   12
#define IDS_SINDYERR_ANNOSTRMOUNTAININVALID 13
#define IDS_SINDYERR_ANNOSTRICJCFTMUSTOVER4 14
#define IDS_SINDYERR_ANNSTRICJCFTBUTLAST2ISNOTICJCFT 15
#define IDS_SINDYERR_ANNOSTRJCBUTLAST3ISNOTJCT 16
#define IDS_SINDYERR_ANNOSTRFIRSTISWIDEZERO 17
#define IDS_SINDYERR_ANNOSTRROUTENUMBEROVERFLOW 18
#define IDS_SINDYERR_ANNOSTRINVALIDCHOUON 19
#define IDS_SINDYERR_ARGLIMITOVER       20
#define SG_IDD_SINDYCONNECTPROPERTYLISTDLG 20480
#define SG_IDD_SINDYCONNECTPROPERTYDLG  20481
#define SG_IDC_LIST_CONNECTPROPERTY     0xD002
#define SG_IDC_BUTTON_ADD               0xD003
#define SG_IDC_BUTTON_DELETE            0xD004
#define SG_IDC_BUTTON_EDIT              0xD005
#define SG_IDC_EDIT_VERSIONDESCRIPTION  0xD006
#define SG_IDC_EDIT_SERVER              0xD007
#define SG_IDC_EDIT_INSTANCE            0xD008
#define SG_IDC_EDIT_USER                0xD009
#define SG_IDC_EDIT_PASSWORD            0xD00A
#define SG_IDC_COMBO_VERSION            0xD00B

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
