/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

#ifndef __SINDY_LOG_TYPE_SELECTOR_H__
#define __SINDY_LOG_TYPE_SELECTOR_H__

#include <iostream>
#include "SiNDYLogHeader.h"

class LogTypeSelector
{
public:
	static SiNDYLogHeader* newLogHeader(std::istream& rSteram, bool bRetainSeekPos);
	static SiNDYLogHeader* newLogHeader(std::wistream& rStream, bool bRetainSeekPos);
};

#endif // __SINDY_LOG_TYPE_SELECTOR_H__
