//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// LQAttrTurnRegDlg.rc で使用
//
#define IDS_PROJNAME                    101
#define IDS_CAPTION                     102
#define IDS_NAME                        103
#define IDS_CATEGORY                    104
#define IDS_TOOLTIP                     105
#define IDS_MESSAGE                     106
#define IDS_BLANKROW                    107
#define IDS_BLANKCELL                   108
#define IDS_SAMESTARTEND                109
#define IDS_ENDLESSDAY                  110
#define IDS_DUPLITIME                   111
#define IDS_SAMETIME                    112
#define IDS_ALLWEEK                     113
#define IDS_INPUT0MONTH                 114
#define IDC_STATIC_SOURCE               167
#define IDC_EDIT_SOURCE                 177
#define IDD_LQATTRTURNREGDLG            765
#define IDC_CHECK_ZEROGATU1             769
#define IDC_CHECK_ZEROGATU2             770
#define IDC_CHECK_ZEROGATU3             771
#define IDC_CHECK_ZEROGATU4             772
#define IDC_CHECK1                      773
#define IDC_STATIC_SOURCESEP            894
#define IDC_COMBO_TURNREGW1             901
#define IDC_COMBO_TURNREGW2             903
#define IDC_COMBO_TURNREGW3             905
#define IDC_COMBO_TURNREGW4             907
#define IDC_BUTTON_SYUJITU1             912
#define IDC_BUTTON_TUUNEN1              914
#define IDC_BUTTON_SYUJITU2             916
#define IDC_BUTTON_SYUJITU3             918
#define IDC_BUTTON_SYUJITU4             920
#define IDC_BUTTON_TUUNEN2              922
#define IDC_BUTTON_TUUNEN3              924
#define IDC_BUTTON_TUUNEN4              926
#define IDC_BUTTON_DELETE1              929
#define IDC_BUTTON_DELETE2              931
#define IDC_BUTTON_DELETE3              933
#define IDC_BUTTON_DELETE4              935
#define IDC_EDIT_TURNREGSMON1           948
#define IDC_EDIT_TURNREGSMON2           949
#define IDC_STATIC_TURNREGSMON1         950
#define IDC_STATIC_TURNREGSMON2         951
#define IDC_EDIT_TURNREGSDAY1           952
#define IDC_STATIC_TURNREGSDAY1         953
#define IDC_STATIC_TURNREGMD1           954
#define IDC_EDIT_TURNREGEMON1           955
#define IDC_STATIC_TURNREGEMON1         956
#define IDC_STATIC_TURNREGEDAY1         957
#define IDC_STATIC_TURNREG1             958
#define IDC_EDIT_TURNREGSDAY2           959
#define IDC_STATIC_TURNREGSDAY2         960
#define IDC_STATIC_TURNREGEHM1          961
#define IDC_EDIT_TURNREGEMIN1           962
#define IDC_STATIC_TURNREGSHM1          963
#define IDC_EDIT_TURNREGEDAY1           964
#define IDC_EDIT_TURNREGSHOUR1          965
#define IDC_EDIT_TURNREGSMIN1           966
#define IDC_EDIT_TURNREGEHOUR1          967
#define IDC_STATIC_TURNREGMD2           968
#define IDC_EDIT_TURNREGEMON2           969
#define IDC_STATIC_TURNREGEMON2         970
#define IDC_STATIC_TURNREGEDAY2         971
#define IDC_EDIT_TURNREGEDAY2           972
#define IDC_EDIT_TURNREGSHOUR2          973
#define IDC_STATIC_TURNREGSHM2          975
#define IDC_EDIT_TURNREGSMIN2           976
#define IDC_EDIT_TURNREGEHOUR2          977
#define IDC_EDIT_TURNREGEMIN2           978
#define IDC_STATIC_TURNREGHM1           979
#define IDC_STATIC_TURNREGHM2           980
#define IDC_STATIC_TURNREGEHM2          982
#define IDC_STATIC_TURNREG2             984
#define IDC_EDIT_TURNREGSMON3           985
#define IDC_STATIC_TURNREGSMON3         986
#define IDC_EDIT_TURNREGSDAY3           987
#define IDC_STATIC_TURNREGSDAY3         988
#define IDC_STATIC_TURNREGMD3           989
#define IDC_EDIT_TURNREGEMON3           990
#define IDC_STATIC_TURNREGEMON3         991
#define IDC_STATIC_TURNREGEDAY3         992
#define IDC_EDIT_TURNREGEDAY3           993
#define IDC_EDIT_TURNREGSHOUR3          994
#define IDC_STATIC_TURNREGSHM3          995
#define IDC_EDIT_TURNREGSMIN3           996
#define IDC_STATIC_TURNREGHM3           997
#define IDC_EDIT_TURNREGEHOUR3          998
#define IDC_EDIT_TURNREGEMIN3           999
#define IDC_STATIC_TURNREGEHM3          1000
#define IDC_STATIC_TURNREG3             1001
#define IDC_EDIT_TURNREGSMON4           1002
#define IDC_STATIC_TURNREGSMON4         1003
#define IDC_EDIT_TURNREGSDAY4           1004
#define IDC_STATIC_TURNREGSDAY4         1005
#define IDC_STATIC_TURNREGMD4           1006
#define IDC_EDIT_TURNREGEMON4           1007
#define IDC_STATIC_TURNREGEMON4         1008
#define IDC_STATIC_TURNREGEDAY4         1009
#define IDC_EDIT_TURNREGEDAY4           1010
#define IDC_EDIT_TURNREGSHOUR4          1011
#define IDC_STATIC_TURNREGSHM4          1012
#define IDC_EDIT_TURNREGSMIN4           1013
#define IDC_STATIC_TURNREGHM4           1014
#define IDC_EDIT_TURNREGEHOUR4          1015
#define IDC_EDIT_TURNREGEMIN4           1016
#define IDC_STATIC_TURNREGEHM4          1017
#define IDC_STATIC_TURNREG4             1018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        272
#define _APS_NEXT_COMMAND_VALUE         32769
#define _APS_NEXT_CONTROL_VALUE         775
#define _APS_NEXT_SYMED_VALUE           305
#endif
#endif
