/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

#pragma once

#define LOG_ERROR	"ERROR"
#define LOG_INFO	"INFO"

#define MWN_LAYER _T("MWN")
#define SQL_NODECLS _T("wkndcls_c = ")

typedef std::map<long, long> MAP_REL_TBL;
typedef std::map<long, WKSPoint> MAP_POI_DATA;

const enum RETURN_TYPE
{
	E_RET_OK,
	E_RET_NG_CONT,
	E_RET_NG_STOP
};

//#define DATA_SET _T("Road")

//#define WALK_OBJECTID 100000000

//#define SGP_RANGE 100.0
