//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// AttrAccessPointDlg.rc で使用
//
#define IDC_STATIC_SOURCE               167
#define IDC_EDIT_SOURCE                 177
#define IDC_EDIT_HOUMENKANJINAME        215
#define IDC_EDIT_HOUMENKANANAME         219
#define IDC_CHECK_INFOMATION            263
#define IDC_CHECK_SPA                   264
#define IDC_CHECK_HWYOASIS              265
#define IDC_CHECK_RESTING               266
#define IDC_CHECK_RESTAURANT            267
#define IDC_CHECK_TOILET                268
#define IDC_CHECK_GS                    269
#define IDC_CHECK_CAFETERIA             270
#define IDC_CHECK_NAP                   271
#define IDC_CHECK_SHOWER                272
#define IDC_CHECK_MAILBOX               273
#define IDS_PROJNAME                    273
#define IDC_CHECK_CARWASH               274
#define IDS_CAPTION                     274
#define IDC_CHECK_HANDYCAP              275
#define IDS_NAME                        275
#define IDC_CHECK_SOUBENIR              276
#define IDS_CATEGORY                    276
#define IDC_CHECK_INFODESK              277
#define IDS_TOOLTIP                     277
#define IDC_CHECK_LAUNDRY               278
#define IDS_MESSAGE                     278
#define IDC_CHECK_CASHSERVICE           279
#define IDS_FAILTOUPDATEACCESSSTORE     279
#define IDC_CHECK_CARWASH2              280
#define IDC_CHECK_DOGRUN                280
#define IDS_CHAINMASTERCODE             280
#define IDS_OPENINGTIME                 281
#define IDS_CLOSINGTIME                 282
#define IDS_INVALID                     283
#define IDS_NOTSAVE                     284
#define IDS_FAILTOSAVEFORUNDO           285
#define IDS_INVALIDASVALUE              286
#define IDS_OPENINGTIMEMIN              287
#define IDS_CLOSINGTIMEMIN              288
#define IDS_FAILTOSETROUTECLASS         289
#define IDS_FAILTOGETROUTECODE          290
#define IDS_FAILTOSETROUTENAME          291
#define IDS_FAILTOGETROW                292
#define IDS_INVALIDDIRSIGNKANA          293
#define IDS_INVALIDDIRSIGNKANJI         294
#define IDS_BASEINFO                    295
#define IDS_INSTITUTIONINFO             296
#define IDS_FACILITYINFO                296
#define IDS_ACCESSSTORE                 297
#define IDS_FONT                        298
#define IDC_EDIT_HOUMENKANJI            352
#define IDC_STATIC_HOUMENKANJI          384
#define IDC_CHECK_HWYMODEFLAG           567
#define IDC_STATIC_ROSENCODE            569
#define IDC_EDIT_SEQUENCE               570
#define IDC_STATIC_SEQUENCE             571
#define IDC_COMBO_DIRECTION             572
#define IDC_STATIC_DIRECTION            573
#define IDC_COMBO_JUNCTIONCODE          576
#define IDC_STATIC_HOUMENKANA           618
#define IDC_EDIT_HOUMENKANA             619
#define IDC_STATIC_JUNCTIONCODE         620
#define IDC_EDIT_ROSENCODE              621
#define IDC_COMBO_ROADCLASS_REF         644
#define IDC_COMBO_ROADNAME_REF          646
#define IDC_STATIC_ROADCLASS_REF        649
#define IDC_STATIC_ROADNAME_REF         650
#define IDC_TAB_ACCESSPOINT             652
#define IDC_CHECK_FAX                   654
#define IDC_COMBO_SEQUENCE              657
#define IDC_STATIC_SEQUENCE_REF         663
#define IDC_STATIC_GS                   664
#define IDC_COMBO_GS                    665
#define IDC_VSFLEXGRIDN1                769
#define IDC_GRID_ACCESS_STORE           769
#define IDC_EDIT_MASTERCODE             770
#define IDC_STATIC_MASTERCODE           771
#define IDC_STATIC_START_TIME           772
#define IDC_STATIC_COLON1               773
#define IDC_EDIT_START_HOUR             774
#define IDC_EDIT_START_MIN              775
#define IDC_EDIT_END_HOUR               776
#define IDC_EDIT_END_MIN                777
#define IDC_STATIC_END_TIME             778
#define IDC_STATIC_COLON2               779
#define IDC_CHECK_MONDAY                780
#define IDC_CHECK_TUESDAY               781
#define IDC_STATIC_MONDAY               782
#define IDC_STATIC_SUNDAY               783
#define IDC_BUTTON_ADD_ACCESS_STORE     784
#define IDC_STATIC_WEDNESDAY            785
#define IDC_STATIC_TUESDAY              786
#define IDC_STATIC_THURSDAY             787
#define IDC_CHECK_WEDNESDAY             788
#define IDC_CHECK_THURSDAY              789
#define IDC_CHECK_FRIDAY                790
#define IDC_CHECK_SATURDAY              791
#define IDC_CHECK_SUNDAY                792
#define IDC_STATIC_SATURDAY             793
#define IDC_STATIC_FRIDAY               794
#define IDC_CHECK_BON                   795
#define IDC_CHECK_YEAREND               796
#define IDC_CHECK_NEWYEAR               797
#define IDC_CHECK_GOLDENWEEK            798
#define IDC_CHECK_HOLIDAY               799
#define IDC_STATIC_YEAREND              800
#define IDC_STATIC_BON                  801
#define IDC_STATIC_NEWYEAR              802
#define IDC_STATIC_HOLIDAY              803
#define IDC_STATIC_GOLDENWEEK           804
#define IDC_BUTTON_CHECK_ALL            805
#define IDC_BUTTON_DELETE_ACCESS_STORE  806
#define IDC_RADIO_GS                    807
#define IDC_BUTTON_UPDATE_ACCESS_STORE  808
#define IDC_BUTTON_UNCHECK_ALL          809
#define IDC_RADIO_CHAIN                 810
#define IDC_GROUP_STORETYPE             811
#define IDC_BUTTON_SAVE_ACCESS          812
#define IDC_BUTTON_SAVE_ACCESS_STORE    812
#define IDC_CHECK_MULTIPLESTORE         1074
#define IDC_STATIC_SHISETUINFO          1180
#define IDD_ATTRACCESSPOINTDLG          10048

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        274
#define _APS_NEXT_COMMAND_VALUE         32769
#define _APS_NEXT_CONTROL_VALUE         812
#define _APS_NEXT_SYMED_VALUE           305
#endif
#endif
