/*
 * Copyright (C) INCREMENT P CORP. All Rights Reserved.
 *
 * THIS SOFTWARE IS PROVIDED BY INCREMENT P CORP., WITHOUT WARRANTY OF
 * ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT.
 *
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDER BE LIABLE FOR ANY
 * CLAIM, DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING
 * OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
*/

#pragma once

#include "stdafx.h"
#include "resource.h"
#include <SizingFramework/include/WinMgr.h>

// ウィンドウマネージャ配置マップ
BEGIN_WINDOW_MAP(ROADSIGN_POINT_MAP)
	BEGINROWS(WRCT_REST, 0, RCMARGINS(5, 5))
			BEGINROWS(WRCT_REST,0,0)
				RCSPACE(10)
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10, 0))
					RCTOFIT(IDC_STATIC_HORIZONTAL_ANGLE)
					RCTOFIT(IDC_EDIT_HORIZONTAL_ANGLE)
					RCSPACE(15)
					RCTOFIT(-1)
					RCREST(IDC_CHECK_VARIABLE_F)
				ENDGROUP()
				RCSPACE(10)
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10, 0))
					RCTOFIT(IDC_STATIC_ROADSIGN_C)
					RCTOFIT(-1)
					RCREST(IDC_COMBO_ROADSIGN_C)
				ENDGROUP()
				RCSPACE(3)
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10, 0))
					RCTOFIT(IDC_STATIC_SEARCH_ROADSIGN_C)
					RCTOFIT(-1)
					RCREST(IDC_EDIT_ROADSIGN_C)
					RCTOFIT(IDC_BUTTON_SEARCH)
				ENDGROUP()
				RCSPACE(10)
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10, 0))
					RCTOFIT(IDC_STATIC_REL_LANE_NODE)
					RCTOFIT(-1)
					RCREST(IDC_VSFLEXGRID_NODE)
				ENDGROUP()
				RCSPACE(10)
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10, 0))
					RCTOFIT(IDC_STATIC_SPECULATION_C)
					RCTOFIT(-1)
					RCREST(IDC_COMBO_SPECULATION_C)
				ENDGROUP()
				RCSPACE(10)
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10, 0))
					RCTOFIT(IDC_STATIC_SOURCE_ID)
					RCTOFIT(-1)
					RCREST(IDC_EDIT_SOURCE_ID)
				ENDGROUP()
			ENDGROUP()
			BEGINROWS(WRCT_TOFIT, 0, RCMARGINS(4, 4))
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(0, 0))
					RCREST(IDC_STATIC_BAR)
				ENDGROUP()
				RCSPACE(5)
				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10, 0))
					RCTOFIT(IDC_STATIC_SOURCE)
					RCTOFIT(-1)
					RCREST (IDC_EDIT_SOURCE)
				ENDGROUP()
				RCSPACE(10)
			ENDGROUP()
	ENDGROUP()
END_WINDOW_MAP()

//
//BEGIN_WINDOW_MAP(ROADSIGN_CLASS_MAP)
//	BEGINROWS(WRCT_REST, 0, RCMARGINS(5, 5))
//		BEGINROWS(WRCT_REST, IDC_TAB_ROADSIGN, RCMARGINS(2, 2))
//			RCSPACE(20)
//			BEGINROWS(WRCT_REST, 0, 0)
//				RCSPACE(10)
//				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10, 0))
//					RCTOFIT(IDC_STATIC_ROADSIGN_C)
//					RCTOFIT(-1)
//					RCREST(IDC_COMBO_ROADSIGN_C)
//				ENDGROUP()
//				RCSPACE(10)
//				BEGINCOLS(WRCT_REST, 0, RCMARGINS(10, 0))
//					RCREST(IDC_LIST_TYPE_ICON)
//				ENDGROUP()
//			ENDGROUP()
//			RCSPACE(10)
//			BEGINROWS(WRCT_TOFIT, 0, RCMARGINS(4, 4))
//				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(0, 0))
//					RCREST(IDC_STATIC_BAR)
//				ENDGROUP()
//				RCSPACE(5)
//				BEGINCOLS(WRCT_TOFIT, 0, RCMARGINS(10, 0))
//					RCTOFIT(IDC_STATIC_SOURCE)
//					RCTOFIT(-1)
//					RCREST(IDC_EDIT_SOURCE)
//				ENDGROUP()
//				RCSPACE(10)
//			ENDGROUP()
//		ENDGROUP()
//	ENDGROUP()
//END_WINDOW_MAP()
